---
apiVersion: v1
kind: LimitRange
metadata:
  name: perf-rhtap-tenant-resource-limits
spec:
  limits:
    - type: "Container"
      default:
        memory: 2Gi
      defaultRequest:
        cpu: 10m
        memory: 64Mi
