---
- name: show the current iteration of the loop at the beginning
  ansible.builtin.debug:
    msg: "start pushing source repo to {{ kflux_data.git_repo_name }}"

- name: check that {{ dockerfile_url }} exists in source repo
  ansible.builtin.stat:
    path: "../{{ git_workspace_dir }}/{{ source_repo_name }}/{{ dockerfile_url }}"
  register: dockerfile_status
  failed_when: not dockerfile_status.stat.exists

- name: push source repo to {{ kflux_data.git_repo_name }}
  ansible.builtin.shell: |
    set -e
    cd ../{{ git_workspace_dir }}/{{ source_repo_name }}
    # Ensure workspace is clean and reset to pristine source revision
    git clean -fd
    git reset --hard source-origin/{{ git_revision }}
    # Setup target remote
    git remote remove origin || true
    git remote add origin git@github.com:{{ github_org }}/{{ kflux_data.git_repo_name }}.git
    git push -f -u origin {{ git_revision }}

- name: show the iteration of the loop at the end
  ansible.builtin.debug:
    msg: "successfully pushed source repo to {{ kflux_data.git_repo_name }}"
