---
- name: show the current iteration of the loop at the beginning
  ansible.builtin.debug:
    msg: "start creating build pipelines for {{ kflux_data.git_repo_name }}"

- name: get details about the remote repository
  ansible.builtin.uri:
    url: "{{ gh_api.base_url + gh_api.get_repository.path }}/{{ kflux_data.git_repo_name }}"
    method: "{{ gh_api.get_repository.method }}"
    headers:
      accept: application/vnd.github+json
      Authorization: "Bearer {{ gh_pat.create_repositories }}"
    status_code: "{{ gh_api.get_repository.expected_status | int }}"
  ignore_errors: true
  retries: "{{ gh_api.retries }}"
  delay: "{{ gh_api.delay_seconds }}"
  until: (get_repository_response.status | int) == (gh_api.get_repository.expected_status | int)
  register: get_repository_response

- name: Debug repository response
  debug:
    var: get_repository_response
    verbosity: 1

- name: prepare pristine workspace
  ansible.builtin.shell: |
    set -e
    cd ../{{ git_workspace_dir }}/{{ source_repo_name }}
    git remote remove {{ kflux_data.git_repo_name }} || true
    git remote add {{ kflux_data.git_repo_name }} {{ get_repository_response.json.ssh_url }}
    git fetch {{ kflux_data.git_repo_name }} {{ git_revision }}
    git clean -fd
    git reset --hard {{ kflux_data.git_repo_name }}/{{ git_revision }}
    git checkout {{ git_revision }}

- name: Create .tekton directory for pipeline files
  ansible.builtin.file:
    path: "../{{ git_workspace_dir }}/{{ source_repo_name }}/.tekton"
    state: directory

- name: Retrieve the latest commit hash from rpmbuild-pipeline main
  ansible.builtin.shell: |
    git ls-remote {{ rpmbuild_pipeline_url }} refs/heads/main | awk '{print $1}'
  register: git_ls_remote_command_status

- name: Set commit hash to use in the build pipelines for revision parameter
  ansible.builtin.set_fact:
    rpmbuild_pipeline_latest_revision: "{{ git_ls_remote_command_status.stdout }}"

- name: render build pipeline templates
  ansible.builtin.template:
    src: ../create-build-pipelines/templates/{{ component_overlay }}/build-pipeline.yaml.j2
    dest: "../{{ git_workspace_dir }}/{{ source_repo_name }}/.tekton/{{ kflux_data.git_repo_name }}-{{ pipeline_type }}.yaml"
  loop:
    - pull-request
    - push
  loop_control:
    loop_var: pipeline_type

- name: create feature branch and commit changes
  ansible.builtin.shell: |
    set -e
    cd ../{{ git_workspace_dir }}/{{ source_repo_name }}
    # Setup target remote
    git remote remove {{ kflux_data.git_repo_name }} || true
    git remote add {{ kflux_data.git_repo_name }} {{ get_repository_response.json.ssh_url }}
    # Delete local branch if exists and recreate from pristine target revision
    git branch -D konflux-{{ kflux_data.git_repo_name }} || true
    git push {{ kflux_data.git_repo_name }} --delete konflux-{{ kflux_data.git_repo_name }} || true
    git checkout -b konflux-{{ kflux_data.git_repo_name }} {{ kflux_data.git_repo_name }}/{{ git_revision }}
    # Rendered templates are now 'untracked', add them
    git add .tekton/
    git commit -m "Add tekton build pipelines"
    # Force push to ensure remote is also clean/reset
    git push -f -u {{ kflux_data.git_repo_name }} konflux-{{ kflux_data.git_repo_name }}
    git checkout {{ git_revision }}

- name: open GitHub pull request
  ansible.builtin.uri:
    url: "{{ gh_api.base_url }}{{ gh_api.create_pull_request.path }}/{{ kflux_data.git_repo_name }}/pulls"
    method: "{{ gh_api.create_pull_request.method }}"
    headers:
      accept: application/vnd.github+json
      Authorization: "Bearer {{ gh_pat.create_repositories }}"
    body_format: json
    body: >
      {
        "head": "konflux-{{ kflux_data.git_repo_name }}",
        "base": "{{ git_revision }}",
        "title": "Add Tekton build pipelines for {{ kflux_data.knflux_comp_name }}"
      }
    status_code: "{{ gh_api.create_pull_request.expected_status | int }}"
  ignore_errors: true
  retries: "{{ gh_api.retries }}"
  delay: "{{ gh_api.delay_seconds }}"
  until: (create_pull_request_response.status | int) == (gh_api.create_pull_request.expected_status | int)
  register: create_pull_request_response

- name: show the iteration of the loop at the end
  ansible.builtin.debug:
    msg: "successfully created build pipelines for {{ kflux_data.git_repo_name }}"
