---
- name: set onboarding failed tenant names to a variable
  ansible.builtin.set_fact:
    failed_tenants: [327, 387, 468, 1108, 1337, 1408, 1409, 1435, 1449, 1582, 1583, 1585, 1586, 1588, 1589, 1590, 1591, 1592, 1593, 1594, 1597, 1598, 1600, 1602, 1604, 1608, 1609, 1610, 1611, 1612, 1615, 1616, 1618, 1619, 1620, 1621, 1624, 1626, 1627, 1628, 1630, 1634, 1635, 1636, 1637, 1638, 1640, 1641, 1643, 1644, 1645, 1648, 1826, 1871, 1874, 1877, 1878, 1880, 1992, 2049, 2053, 2058, 2070, 2149, 2150, 2151, 2153, 2155, 2156, 2157, 2160, 2162, 2165, 2166, 2167, 2169, 2172, 2173, 2174, 2175, 2178, 2180, 2181, 2182, 2185, 2186, 2187, 2188, 2190, 2192, 2194, 2195, 2196, 2197, 2198, 2199, 2202, 2203, 2204, 2205, 2208, 2209, 2210, 2211, 2212, 2215, 2217, 2222, 2223, 2226, 2228, 2229, 2231, 2232, 2237, 2238, 2243, 2244, 2245, 2258, 2344, 2399, 2402, 2404, 2405, 2411, 2412, 2413, 2414, 2415, 2416, 2417, 2418, 2419, 2420, 2421, 2422, 2423, 2424, 2425, 2426, 2427, 2428, 2429, 2430, 2431, 2438, 2439, 2440, 2442, 2445, 2457, 2458, 2470, 2471, 2473, 2476, 2482, 2485, 2489, 2496, 2497, 2510, 2642, 2739, 2775, 2816, 2817, 2818, 2819, 2821, 2822, 2823, 2825, 2826, 2827, 2828, 2829, 2830, 2831, 2832, 2833, 2834, 2835, 2836, 2837, 2838, 2839, 2840, 2842, 2843, 2844, 2946, 2964, 2965, 2966, 2968, 2969, 2970, 2971, 2972, 2973]

- name: generate GitHub repository name list
  ansible.builtin.set_fact:
    github_repository_names: "{% set tmp_repo_names = [] %}{% for item in range(starts_from|int, ends_at|int + 1) %}{% if item in failed_tenants %}{{ tmp_repo_names.append({'key': 'git_repo_name', 'value': repository_name_prefix + (item | string)}) }}{% endif %}{% endfor %}{{ tmp_repo_names }}"

- name: generate Konflux application name lists
  ansible.builtin.set_fact:
    konflux_application_names: "{% set tmp_app_names = [] %}{% for item in range(starts_from|int, ends_at|int + 1) %}{% if item in failed_tenants %}{{ tmp_app_names.append({'key': 'knflux_app_name', 'value': 'example-packages'}) }}{% endif %}{% endfor %}{{ tmp_app_names }}"
    
- name: generate Konflux component name lists
  ansible.builtin.set_fact:
      konflux_component_names: "{% set tmp_comp_names = [] %}{% for item in range(starts_from|int, ends_at|int + 1) %}{% if item in failed_tenants %}{{ tmp_comp_names.append({'key': 'knflux_comp_name', 'value': 'example-rok-libecpg'}) }}{% endif %}{% endfor %}{{ tmp_comp_names }}"

- name: generate tenant names for rok scenario
  ansible.builtin.set_fact:
    konflux_tenant_names: "{% set tmp_rok_tenants = [] %}{% for item in range(starts_from|int, ends_at|int + 1) %}{% if item in failed_tenants %}{{ tmp_rok_tenants.append({'key': 'knflux_tenant_name', 'value': rok_tenant_namespace_prefix + (item | string) + rok_tenant_namespace_suffix }) }}{% endif %}{% endfor %}{{ tmp_rok_tenants }}"
  when: test_scenario == 'rok'

- name: generate tenant names for fkx scenario
  ansible.builtin.set_fact:
    konflux_tenant_names: "{% set tmp_fkx_tenants = [] %}{% for item in range(starts_from|int, ends_at|int + 1) %}{{ tmp_fkx_tenants.append({'key': 'knflux_tenant_name', 'value': fedora_tenant_namespace }) }}{% endfor %}{{ tmp_fkx_tenants }}"
  when: test_scenario == 'fkx'

- name: zip Konflux applications, components, tenant namespaces and GitHub repositories
  ansible.builtin.set_fact:
    konflux_zipped_data: "{{ konflux_application_names | zip(github_repository_names, konflux_component_names, konflux_tenant_names) }}"

- name: convert zipped Konflux app/component/repo data to list of dictionaries
  ansible.builtin.set_fact:
    konflux_mapped_data: "{% set tmp_map_values=[] %}{% for item in konflux_zipped_data %}{{ tmp_map_values.append(item | items2dict) }}{% endfor %}{{ tmp_map_values }}"

- name: debug generated name list
  ansible.builtin.debug:
    msg: 
    - "github_repository_names  : {{ github_repository_names }}"
    - "konflux_application_names: {{ konflux_application_names}}"
    - "konflux_component_names  : {{ konflux_component_names }}"
    - "konflux_tenant_names     : {{ konflux_tenant_names }}"
    verbosity: 1

- name: debug konflux mapped data
  ansible.builtin.debug:
    var: konflux_mapped_data
    verbosity: 1

- name: calculate total range
  ansible.builtin.set_fact:
    total_items_count: "{{ (ends_at|int - starts_from|int) + 1 }}"

    #- name: verify length of the generated name list
    #ansible.builtin.assert:
    #that:
    #  - github_repository_names | length == total_items_count | int
    #  - konflux_application_names | length == total_items_count | int
    #  - konflux_component_names | length == total_items_count | int
    #  - konflux_tenant_names | length == total_items_count | int
    #  - konflux_mapped_data | length == total_items_count | int
    #success_msg: 
    #  - "All assertions passed"
    #  - "Total items in the generated name list matches the total range ({{ total_items_count }}) defined"
