---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  name: jhutar-app-rp
  namespace: konflux-tenant
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
    release.appstudio.openshift.io/standing-attribution: 'true'
spec:
  application: app
  releaseGracePeriodDays: 7
  target: konflux-tenant
