---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - application.yaml
  - component.yaml
  - konflux-perf-scale-release-plan.yaml
  - integration-test-scenario.yaml
  - release-plan-admission.yaml
  - enterprise-contract-policy.yaml
  - push-secret.yaml
